### ISSUE TITLE
Can you add `tikz` figure rendering?

### ISSUE THREAD

**Issue by m-yaghini** [xyhp915/logseq-fenced-code-plus#17]
Hello and thank you for this wonderful plugin. 

Can you add [tikzjax](https://github.com/kisonecat/tikzjax) rendering similar to mermaid? 

There is a similar plugin for obsidian, [obsidian-tikzjax](https://github.com/artisticat1/obsidian-tikzjax) that uses forks of the original library for added functionality. 

I have tried to add this myself but since tikzjax does not have a .render function, it is difficult to call it async; as it is only loaded on load of a (conventional) webpage. obsidian-tikzjax gets around this issue by custom event listeners. 

Having said that, there is a live demo here: https://tikzjax-demo.glitch.me which I could not compile locally. 

Thanks again for your elegant work here.

**Comment by meain** [comment]
I guess this can now be closed.

**Comment by m-yaghini** [comment]
Can you clarify? Is there an update supporting tikz? or this is not a priority?

**Comment by Junior-Wang** [comment]
re-edit: 

Problem solved. **Have to enable it in plugin settings** for some one have the same issue.


> ~Can you clarify? Is there an update supporting tikz? or this is not a priority?~ Edit: Indeed the tikzjax has been added! I did not realize since this is not documented yet in the README. I just tested it, and it works great!
> 
> Thank you so much!
> 
> Closing.

Hi @m-yaghini . 

I'm using **logseq 0.10.9** on **windows 10** with this latested (version **0.0.11**) plugin installed. But the tikz graph did not renered at all or even did report an error.

I have also tried building this plugin locally **"logseq 0.10.10-alpha+nightly.20240812"** on **window 11** with npm. tikz code block did not work as well as shown below.

![Image](https://github.com/user-attachments/assets/e87f2569-80f7-4094-8b94-7624f14f09d7)

I also tried `tikz` and `tikzjax` keyword. But the tikz still did not work.

```markdown
```tikzjax
\draw (0,0) circle (1in);
```

Can you show me how did you use this plugin to render tikz figure please?
