### ISSUE TITLE
Update Mermaid 10

### ISSUE THREAD

**Issue by Hajiku68** [xyhp915/logseq-fenced-code-plus#20]
Please update to the latest Mermaid to apply the mindmaps diagram,
Thanks

**Comment by garderobier** [comment]
I would like to see that as well. Timeline diagrams are not supported right now.
<img width="494" alt="grafik" src="https://user-images.githubusercontent.com/101436860/236924135-4dfc9db4-81c9-4676-b0d8-21cd022a951d.png">
