### ISSUE TITLE
Adding theme configurations gives syntax error

### ISSUE THREAD

**Issue by AvijeetPrasad** [xyhp915/logseq-fenced-code-plus#3]
Hi, I am trying to use the theme settings as follows

```
%%{init: {'theme':'base'}}%%
  graph LR
  a --> b
```

```mermaid
%%{init: {'theme':'base'}}%%
  graph LR
  a --> b
```

As can be seen above, it renders fine in GitHub, but on Logseq `0.6.9` with version `0.0.3` of the plugin, it shows a syntax error. Maybe the mermaid version needs to be updated?

This would be really useful when we are switching from light and dark modes in Logsesq.

**Comment by xyhp915** [comment]
I found it works for me :)
https://user-images.githubusercontent.com/1779837/170442213-25d30df8-5e34-459a-a6b8-d77bec5fb0d9.mp4
