### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by yoyurec** [xyhp915/logseq-fenced-code-plus#4]
Simple code, but got error.
![image](https://user-images.githubusercontent.com/137919/169667817-b5a93dcf-406a-44d7-8565-bbe99aced7d8.png)
Plugin worked some time and then any code not rendered anymore (((
Uninstall, install, reload Logseq - nothing help ((

![image](https://user-images.githubusercontent.com/137919/169667853-008d64f6-236e-4708-9f44-e089aa1519fb.png)

**Comment by xyhp915** [comment]
Hi @yoyurec  What's the version of the Desktop app?

**Comment by yoyurec** [comment]
0.7.0, Windows

**Comment by peizh** [comment]
same error on Mac OS, Version 0.7.1 (0.7.1)

**Comment by eBerdnA** [comment]
Does work for me on version 0.8.4 of the desktop app.
@yoyurec Do you still this issue on your side?

**Comment by yoyurec** [comment]
works good now!
