### ISSUE TITLE
bump mermaid version

### ISSUE THREAD

**Issue by znd4** [xyhp915/logseq-fenced-code-plus#43]
Hi, [as of 10.6.0](https://github.com/mermaid-js/mermaid/releases/tag/v10.6.0), mermaid has a cool xychart that seems really useful. I would try doing this in a PR, but I'm guessing upgrading a vendored library is something that should really only be done by you the maintainer, since the diff will probably be impossible to review.

Thanks for this awesome plugin :)

**Comment by xyhp915** [comment]
Hi @znd4 fixed in latest version #35
