### ISSUE TITLE
Suggestion : does any chance can support Block Diagrams

### ISSUE THREAD

**Issue by NYX-shell** [xyhp915/logseq-fenced-code-plus#45]
As the title is written, using a mermaid to genera a flowchart is very useful. but it's still not enough to provide a high-level view of a system, because the automatic layout will move shape positions.
we can see in the official document of Mermaid, they provide another diagram called Block Diagrams that can solve this problem.
https://mermaid.js.org/syntax/block.html
Is there any chance you can support these diagrams?

**Comment by mcmoe** [comment]
Block diagram has been introduced at 10.8.0 (see https://github.com/mermaid-js/mermaid/releases)
Therefore this will require the upgrade of mermaid.js in this repo to >= `10.8.0`. It is currently at `10.7.0`.

A commit similar to the following with updated mermaid files: https://github.com/xyhp915/logseq-fenced-code-plus/commit/1030f00a5f8916cf6b19833b956ff19d765d892a.
