### ISSUE TITLE
Astro

### ISSUE THREAD

**Issue by paulrudy** [xyhp915/logseq-fenced-code-plus#5]
Hi, would you consider adding .astro syntax?

[VSCode plugin](https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode) for reference if that helps

**Comment by Bad3r** [comment]
This seems out of the scope of the plugin. This is mainly used for crating diagrams. Not sure how Astro fits in here.

**Comment by paulrudy** [comment]
Oh, I'm sorry, I misunderstood the purpose of the plugin. I had thought it was for general fenced code of various programming languages.

**Comment by Bad3r** [comment]
@paulrudy do you mean adding syntax highlighting for Astro? Logseq uses code mirror

**Comment by paulrudy** [comment]
Thanks @Bad3r, yes that's what I meant

**Comment by Bad3r** [comment]
@paulrudy feel free to move the issue to: https://github.com/xyhp915/logseq-extensions-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed
