### ISSUE TITLE
Theming for mermaid

### ISSUE THREAD

**Issue by jkrude** [xyhp915/logseq-fenced-code-plus#7]
First of all thank you for this very useful plugin!
As I mostly use dark-mode-themes with logseq it would be extremely useful if the mermaid-theming could be adjusted. Unfortunately, I'm not a web developer, but I guess you could change the theme to the system default [here](https://github.com/xyhp915/logseq-fenced-code-plus/blob/7cbbe4fcb470e8302165b62c4c21999bd25f305b/src/mermaid.tsx#L38) by adding:
```js
host.mermaid.initialize({
  theme: (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) ?
    "dark" :
    "default"
})
```
Further, I am not sure if the internal logseq setting for dark mode could be directly queried.
Otherwise, an option could be added for the plugin where the user can choose between the themes available by default and the `%%{init: {'theme': 'theme-name' }}%%` line is automatically injected.

[Mermaid theming docs.](https://github.com/mermaid-js/mermaid/blob/79636af9f9c707b284a75088b4f76e5785f00562/docs/theming.md)

**Comment by AhmedThahir** [comment]
Will the above code work?
Any updates on this?

**Comment by DerAnderDo** [comment]
> Will the above code work? Any updates on this?

Yes, if you add %%{init: {'theme': 'dark' } }%% at the start of your mermaid code, it will be in dark mode.

Example:

```mermaid
%%{init: {'theme': 'dark' } }%%
graph TD
    blablablabla.....
```

Of course this is just a workaround and having mermaid dynamically configured by reading the logseq system theme would be much handier.
