### ISSUE TITLE
GitGraph not working

### ISSUE THREAD

**Issue by eBerdnA** [xyhp915/logseq-fenced-code-plus#9]
**Description**:
Right now `gitGraph` doesn't seem to be working with desktop version `0.8.4`. All other graph types are working fine for me.

**Possible solution**:
From what I understand there was an issue with [mermaid](https://github.com/mermaid-js/mermaid) at least that's how I understand the following issue: [Git Charts not working · Issue #3306 · mermaid-js/mermaid](https://github.com/mermaid-js/mermaid/issues/3306)
The fix for this seems to be included in the lastet release `9.1.6`. Therefore a bump of the included mermaid version here should solve this.

**Comment by xyhp915** [comment]
Thanks @eBerdnA It's fixed in the latest version (0.0.4)

**Comment by eBerdnA** [comment]
Perfect. 👍 Just updated the plugin and can confirm it's working on my side.
